apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .secretName }}
  namespace: {{ .namespace }}
spec:
  type: kv-v2

  mount: kvv2
  path: {{ .path }}

  destination:
    name: {{ .secretName }}
    create: true

  vaultAuthRef: default