{{- range .Values.staticSecrets }}
{{- if ne .enabled false }}
{{- $defaults := $.Values.defaults }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ required "staticSecrets[].name is required" .name }}
  namespace: {{ required "staticSecrets[].namespace is required" .namespace }}
spec:
  vaultAuthRef: {{ .vaultAuthRef | default $defaults.vaultAuthRef }}
  mount: {{ .mount | default $defaults.mount }}
  type: {{ .type | default $defaults.type }}
  path: {{ required "staticSecrets[].path is required" .path }}
  refreshAfter: {{ .refreshAfter | default $defaults.refreshAfter }}
  destination:
    name: {{ dig "destination" "name" .name . }}
    create: {{ dig "destination" "create" true . }}
    overwrite: {{ dig "destination" "overwrite" true . }}
    {{- with dig "destination" "labels" nil . }}
    labels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with dig "destination" "type" "" . }}
    type: {{ . }}
    {{- end }}
    {{- $transform := .transformation | default "" }}
    {{- if eq $transform "dockerconfigjson" }}
    transformation:
      {{- toYaml $.Values.transformations.dockerconfigjson | nindent 6 }}
    {{- else if eq $transform "minioconn" }}
    transformation:
      {{- toYaml $.Values.transformations.minioconn | nindent 6 }}
    {{- else if dig "destination" "transformation" nil . }}
    transformation:
      {{- toYaml (dig "destination" "transformation" dict .) | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
