{{- $root := . }}
{{- with .Values.controllers }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controllers
  labels:
    {{- include "kafka.labels" $root | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ required "controllers.replicas is required" .replicas }}
  roles:
    - controller
  storage:
    type: {{ required "controllers.storage.type is required" .storage.type }}
    {{- if eq .storage.type "persistent-claim" }}
    size: {{ required "controllers.storage.size is required" .storage.size }}
    deleteClaim: {{ .storage.deleteClaim | default false }}
    {{- with .storage.class }}
    class: {{ . }}
    {{- end }}
    {{- with .storage.id }}
    id: {{ . }}
    {{- end }}
    {{- end }}
  {{- with .resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .jvmOptions }}
  jvmOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .template }}
  template:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
