{{- $root := . }}
{{- $entity := .Values.entityOperator }}
{{- $exporter := .Values.kafkaExporter }}
{{- $cruise := .Values.cruiseControl }}
{{- with .Values.kafka }}
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ include "kafka.clusterName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  {{- with .metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  kafka:
    version: {{ .version | quote }}
    metadataVersion: {{ .version | quote }}
    listeners:
      {{- toYaml .listeners | nindent 6 }}
    config:
      {{- toYaml .config | nindent 6 }}
    {{- with .jvmOptions }}
    jvmOptions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .logging }}
    logging:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .template }}
    template:
      {{- toYaml .template | nindent 6 }}
    {{- end }}
  {{- if $entity.enabled }}
  entityOperator:
    {{- if $entity.topicOperator }}
    topicOperator:
      {{- toYaml $entity.topicOperator | nindent 6 }}
    {{- else }}
    topicOperator: {}
    {{- end }}
    {{- if $entity.userOperator }}
    userOperator:
      {{- toYaml $entity.userOperator | nindent 6 }}
    {{- else }}
    userOperator: {}
    {{- end }}
  {{- end }}
  {{- if $exporter.enabled }}
  kafkaExporter:
    {{- if $exporter.spec }}
    {{- toYaml $exporter.spec | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  {{- end }}
  {{- if $cruise.enabled }}
  cruiseControl:
    {{- if $cruise.spec }}
    {{- toYaml $cruise.spec | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  {{- end }}
{{- end }}
