imageRegistry: quay.io
imageRepository: apicurio
imagePullSecrets:
  - name: dockerhub-regcred

operator:
  replicas: 1
  image:
    name: apicurio-registry-3-operator
    tag: "3.3.0"
    
app:
  name: apicurio-registry
  tag: "3.3.0"
ui:
  name: apicurio-registry-ui
  tag: "3.3.0"
gitops:
  name: apicurio-registry-gitops-sync
  tag: "3.3.0"

serviceAccount:
  name: "apicurio-registry-operator"
