# Strimzi Kafka cluster (production). Bootstrap: <clusterName>-kafka-bootstrap.<namespace>.svc:9092
clusterName: dp-kafka

nameOverride:

# KafkTopic
# Docs: https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaTopic-reference
# name: metadata resources
# topicName: name of topics
# partitions: number of partitions
# config (optional): docs: https://kafka.apache.org/41/configuration/topic-configs/
# ---
# CONVENTION: 
# domain.entity.variant
# domain: cdc
# entity: orders, customers
# variant (optional): env, version: v1, raw, prod
topics:
  - name: cdc-order-topics
    topicName: cdc.orders
    partitions: 6