# Strimzi Kafka cluster (production). Bootstrap: <clusterName>-kafka-bootstrap.<namespace>.svc:9092
clusterName: dp-kafka

imagePullSecrets: []
  # - name: dockerhub-regcred

# Kafka configuration 
# doc: https://strimzi.io/docs/operators/latest/configuring.html#type-Kafka-reference
kafka:
  version: "4.2.0"
  metadata:
    labels: {}
    annotations:
      # enabled: https://strimzi.io/blog/2023/08/14/kafka-node-pools-introduction/
      strimzi.io/node-pools: enabled

  # 6.2 Specifying listener types
  # https://strimzi.io/docs/operators/latest/configuring.html#specifying_listener_types
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true

  # 5. KafkaClusterSpec schema reference
  # https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaClusterSpec-reference
  # https://kafka.apache.org/43/configuration/broker-configs/
  config:
    auto.create.topics.enable: false
    # num replicas per partition
    default.replication.factor: 3
    # topic: __consumer_offsets: num replicas offsets topics
    offsets.topic.replication.factor: 3
    # min partitions created
    num.partitions: 3
    # min followers in-sync with leader
    min.insync.replicas: 2
    # __transaction_state: store state transaction kafka
    transaction.state.log.replication.factor: 3
    # min in-sync with leader
    transaction.state.log.min.isr: 2
    # time keeps messages
    log.retention.hours: 168

  # 19. JvmOptions schema reference
  # https://strimzi.io/docs/operators/latest/configuring.html#property-kafka-logging-reference
  jvmOptions:
    -Xms: 2g
    -Xmx: 2g

  # 5.2. Logging
  # https://strimzi.io/docs/operators/latest/configuring.html#property-kafka-logging-reference
  logging:
    type: inline
    loggers:
      rootLogger.level: INFO
      logger.requestlogger.level: WARN
      logger.requestchannel.level: WARN
      logger.authorizer.level: INFO

entityOperator:
  enabled: true

kafkaExporter:
  enabled: false

cruiseControl:
  enabled: false

# kafka controller definitions
# https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaNodePool-reference
controllers:
  replicas: 3
  storage:
    type: PersistentClaimStorage
    size: 20Gi
    class: longhorn
    deleteClaim: false
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  jvmOptions:
    -Xms: 1g
    -Xmx: 1g
  template:
    pod:
      imagePullSecrets:
        - name: dockerhub-regcred
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  strimzi.io/cluster: dp-kafka
                  strimzi.io/pool-name: controllers
              topologyKey: kubernetes.io/hostname

# kafka brokers definitions
# https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaNodePool-reference
brokers:
  replicas: 3
  storage:
    type: persistent-claim
    size: 100Gi
    class: longhorn
    deleteClaim: false
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 8Gi
  jvmOptions:
    -Xms: 2g
    -Xmx: 2g
  template:
    pod:
      imagePullSecrets:
        - name: dockerhub-regcred
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  strimzi.io/cluster: dp-kafka
                  strimzi.io/pool-name: brokers
              topologyKey: kubernetes.io/hostname
